"use client";

import { useMemo, useState } from "react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  Cell,
  Pie,
  PieChart,
  XAxis,
  YAxis,
} from "recharts";
import {
  ArrowDownRight,
  ArrowUpRight,
  Download,
  Link2,
  MousePointerClick,
  Search,
  Target,
  TrendingUp,
  UserPlus,
} from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/shared/page-header";
import { StatCard } from "@/components/shared/stat-card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/components/ui/chart";
import { EmptyState } from "@/components/shared/empty-state";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  UTM_BY_MEDIUM,
  UTM_BY_SOURCE,
  UTM_CAMPAIGNS,
  UTM_KPIS,
  UTM_TREND,
} from "@/lib/mock-data";
import { formatDate } from "@/lib/format";
import { cn } from "@/lib/utils";

const SOURCE_SERIES = [
  { key: "google", label: "Google", color: "var(--chart-1)" },
  { key: "linkedin", label: "LinkedIn", color: "var(--chart-2)" },
  { key: "newsletter", label: "Newsletter", color: "var(--chart-3)" },
  { key: "event", label: "Event", color: "var(--chart-4)" },
  { key: "referral", label: "Referral", color: "var(--chart-5)" },
];

const trendConfig: ChartConfig = Object.fromEntries(
  SOURCE_SERIES.map((s) => [s.key, { label: s.label, color: s.color }])
);

const MEDIUM_COLORS = [
  "var(--chart-1)",
  "var(--chart-2)",
  "var(--chart-3)",
  "var(--chart-4)",
  "var(--chart-5)",
  "var(--muted-foreground)",
];

function Delta({ value }: { value: number }) {
  const positive = value >= 0;
  return (
    <span
      className={cn(
        "inline-flex items-center gap-0.5 text-xs font-medium tabular-nums",
        positive ? "text-emerald-600" : "text-red-600"
      )}
    >
      {positive ? (
        <ArrowUpRight className="size-3" />
      ) : (
        <ArrowDownRight className="size-3" />
      )}
      {Math.abs(value).toFixed(1)}%
    </span>
  );
}

type SortKey = "leads" | "cvr";

export function UtmAnalytics() {
  const [range, setRange] = useState("30d");
  const [sourceFilter, setSourceFilter] = useState("all");
  const [mediumFilter, setMediumFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [sortKey, setSortKey] = useState<SortKey>("leads");

  const sources = useMemo(
    () => Array.from(new Set(UTM_CAMPAIGNS.map((c) => c.source))),
    []
  );
  const mediums = useMemo(
    () => Array.from(new Set(UTM_CAMPAIGNS.map((c) => c.medium))),
    []
  );

  const filteredCampaigns = useMemo(() => {
    const q = search.toLowerCase();
    return UTM_CAMPAIGNS.filter((c) => {
      if (sourceFilter !== "all" && c.source !== sourceFilter) return false;
      if (mediumFilter !== "all" && c.medium !== mediumFilter) return false;
      if (q && !`${c.campaign} ${c.source} ${c.medium} ${c.content ?? ""}`.toLowerCase().includes(q))
        return false;
      return true;
    }).sort((a, b) => b[sortKey] - a[sortKey]);
  }, [sourceFilter, mediumFilter, search, sortKey]);

  const maxSourceLeads = Math.max(...UTM_BY_SOURCE.map((s) => s.leads), 1);

  return (
    <div className="space-y-6">
      <PageHeader
        title="UTM Analytics"
        description="Leads generated by UTM source, medium, and campaign — attribution across every channel."
        actions={
          <div className="flex items-center gap-2">
            <Select value={range} onValueChange={(v) => setRange(v ?? "30d")}>
              <SelectTrigger className="w-36">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7d">Last 7 days</SelectItem>
                <SelectItem value="30d">Last 30 days</SelectItem>
                <SelectItem value="90d">Last 90 days</SelectItem>
                <SelectItem value="qtd">Quarter to date</SelectItem>
              </SelectContent>
            </Select>
            <Button
              variant="outline"
              onClick={() => toast.success("Export queued — CSV will download shortly")}
            >
              <Download className="size-4" /> Export
            </Button>
          </div>
        }
      />

      {/* KPIs */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Attributed leads"
          value={UTM_KPIS.totalLeads.toLocaleString()}
          subtitle="From UTM-tagged traffic"
          icon={UserPlus}
          trend={{ value: `+${UTM_KPIS.totalLeadsDeltaPct}% vs prev.`, positive: true }}
        />
        <StatCard
          title="Tagged sessions"
          value={UTM_KPIS.taggedSessions.toLocaleString()}
          subtitle="Visits carrying UTM params"
          icon={MousePointerClick}
          trend={{ value: `+${UTM_KPIS.taggedSessionsDeltaPct}% vs prev.`, positive: true }}
        />
        <StatCard
          title="Top source"
          value={UTM_KPIS.topSource}
          subtitle={`${UTM_KPIS.topSourceLeads} leads`}
          icon={Target}
        />
        <StatCard
          title="Lead → customer"
          value={`${UTM_KPIS.cvr}%`}
          subtitle="Blended conversion"
          icon={TrendingUp}
          trend={{ value: `+${UTM_KPIS.cvrDeltaPct} pts`, positive: true }}
        />
      </div>

      {/* Trend */}
      <Card className="shadow-none">
        <CardHeader>
          <CardTitle className="text-base">Leads over time by source</CardTitle>
          <CardDescription>New leads attributed to each UTM source.</CardDescription>
        </CardHeader>
        <CardContent>
          <ChartContainer config={trendConfig} className="h-[260px] w-full">
            <AreaChart data={UTM_TREND} margin={{ left: 4, right: 4, top: 4 }}>
              <defs>
                {SOURCE_SERIES.map((s) => (
                  <linearGradient key={s.key} id={`fill-${s.key}`} x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor={s.color} stopOpacity={0.28} />
                    <stop offset="95%" stopColor={s.color} stopOpacity={0.03} />
                  </linearGradient>
                ))}
              </defs>
              <CartesianGrid vertical={false} strokeDasharray="3 3" />
              <XAxis dataKey="label" tickLine={false} axisLine={false} tickMargin={8} />
              <YAxis tickLine={false} axisLine={false} width={36} />
              <ChartTooltip content={<ChartTooltipContent />} />
              {SOURCE_SERIES.map((s) => (
                <Area
                  key={s.key}
                  type="monotone"
                  dataKey={s.key}
                  stackId="1"
                  stroke={s.color}
                  fill={`url(#fill-${s.key})`}
                  strokeWidth={2}
                />
              ))}
            </AreaChart>
          </ChartContainer>
        </CardContent>
      </Card>

      {/* Source + Medium breakdown */}
      <div className="grid gap-6 lg:grid-cols-5">
        <Card className="shadow-none lg:col-span-3">
          <CardHeader>
            <CardTitle className="text-base">Leads by source</CardTitle>
            <CardDescription>source / medium pairs, ranked by leads.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {UTM_BY_SOURCE.map((s) => (
              <div key={`${s.source}-${s.medium}`} className="space-y-1.5">
                <div className="flex items-center justify-between text-sm">
                  <span className="flex items-center gap-2 font-medium">
                    {s.source}
                    <Badge variant="outline" className="border-0 bg-muted text-xs text-muted-foreground">
                      {s.medium}
                    </Badge>
                  </span>
                  <span className="flex items-center gap-3">
                    <span className="tabular-nums">{s.leads.toLocaleString()}</span>
                    <Delta value={s.deltaPct} />
                  </span>
                </div>
                <div className="h-2 overflow-hidden rounded-full bg-muted">
                  <div
                    className="h-full rounded-full bg-primary"
                    style={{ width: `${(s.leads / maxSourceLeads) * 100}%` }}
                  />
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card className="shadow-none lg:col-span-2">
          <CardHeader>
            <CardTitle className="text-base">Leads by medium</CardTitle>
            <CardDescription>Share of attributed leads.</CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer config={{}} className="mx-auto aspect-square max-h-[220px]">
              <PieChart>
                <ChartTooltip content={<ChartTooltipContent nameKey="label" hideLabel />} />
                <Pie
                  data={UTM_BY_MEDIUM}
                  dataKey="leads"
                  nameKey="label"
                  innerRadius={52}
                  outerRadius={82}
                  paddingAngle={2}
                >
                  {UTM_BY_MEDIUM.map((_, i) => (
                    <Cell key={i} fill={MEDIUM_COLORS[i % MEDIUM_COLORS.length]} />
                  ))}
                </Pie>
              </PieChart>
            </ChartContainer>
            <div className="mt-2 space-y-1.5">
              {UTM_BY_MEDIUM.map((m, i) => (
                <div key={m.key} className="flex items-center justify-between text-xs">
                  <span className="flex items-center gap-2">
                    <span
                      className="size-2.5 rounded-full"
                      style={{ background: MEDIUM_COLORS[i % MEDIUM_COLORS.length] }}
                    />
                    {m.label}
                  </span>
                  <span className="tabular-nums text-muted-foreground">
                    {m.leads} · {m.share}%
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Detailed table */}
      <Card className="shadow-none">
        <CardHeader className="gap-3">
          <div className="flex flex-col gap-1">
            <CardTitle className="text-base">Campaign attribution</CardTitle>
            <CardDescription>Every UTM combination and the leads it produced.</CardDescription>
          </div>
          <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
            <div className="relative flex-1">
              <Search className="absolute top-1/2 left-2.5 size-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                className="pl-8"
                placeholder="Search campaign, source, content…"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <Select value={sourceFilter} onValueChange={(v) => setSourceFilter(v ?? "all")}>
              <SelectTrigger className="w-full sm:w-40">
                <SelectValue placeholder="Source" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All sources</SelectItem>
                {sources.map((s) => (
                  <SelectItem key={s} value={s}>
                    {s}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Select value={mediumFilter} onValueChange={(v) => setMediumFilter(v ?? "all")}>
              <SelectTrigger className="w-full sm:w-40">
                <SelectValue placeholder="Medium" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All mediums</SelectItem>
                {mediums.map((m) => (
                  <SelectItem key={m} value={m}>
                    {m}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {filteredCampaigns.length === 0 ? (
            <div className="p-6">
              <EmptyState
                icon={Link2}
                title="No matching UTM data"
                description="Try clearing filters or widening the date range."
              />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Campaign</TableHead>
                  <TableHead>Source / Medium</TableHead>
                  <TableHead className="hidden md:table-cell">Content</TableHead>
                  <TableHead
                    className="cursor-pointer text-right select-none"
                    onClick={() => setSortKey("leads")}
                  >
                    Leads {sortKey === "leads" && "↓"}
                  </TableHead>
                  <TableHead className="hidden text-right sm:table-cell">Sessions</TableHead>
                  <TableHead
                    className="cursor-pointer text-right select-none"
                    onClick={() => setSortKey("cvr")}
                  >
                    CVR {sortKey === "cvr" && "↓"}
                  </TableHead>
                  <TableHead className="hidden text-right lg:table-cell">Last seen</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredCampaigns.map((c) => (
                  <TableRow key={c.id}>
                    <TableCell className="font-medium">{c.campaign}</TableCell>
                    <TableCell>
                      <span className="flex flex-wrap items-center gap-1.5">
                        <Badge variant="outline" className="capitalize">{c.source}</Badge>
                        <span className="text-muted-foreground">/</span>
                        <Badge variant="outline" className="border-0 bg-muted text-muted-foreground">
                          {c.medium}
                        </Badge>
                      </span>
                    </TableCell>
                    <TableCell className="hidden font-mono text-xs text-muted-foreground md:table-cell">
                      {c.content ?? "—"}
                    </TableCell>
                    <TableCell className="text-right font-medium tabular-nums">
                      {c.leads.toLocaleString()}
                    </TableCell>
                    <TableCell className="hidden text-right tabular-nums text-muted-foreground sm:table-cell">
                      {c.sessions.toLocaleString()}
                    </TableCell>
                    <TableCell className="text-right tabular-nums">{c.cvr}%</TableCell>
                    <TableCell className="hidden text-right text-xs text-muted-foreground lg:table-cell">
                      {formatDate(c.lastSeen)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
