import type {
  DocumentRequestTemplate,
  MagicLinkSession,
  OutreachDispatch,
} from "@/lib/types";

export const DOCUMENT_REQUEST_TEMPLATES: DocumentRequestTemplate[] = [
  {
    id: "drt1",
    name: "Vendor onboarding — India",
    description: "Standard KYC pack for new vendor registration.",
    category: "onboarding",
    defaultTtlDays: 7,
    defaultChannels: ["email", "whatsapp"],
    items: [
      {
        id: "di1",
        label: "Company PAN card",
        description: "Clear scan or photo. PDF or JPG only.",
        required: true,
        acceptedFormats: ["PDF", "JPG", "PNG"],
        maxSizeMb: 5,
      },
      {
        id: "di2",
        label: "GST registration certificate",
        description: "Latest certificate from government portal.",
        required: true,
        acceptedFormats: ["PDF"],
        maxSizeMb: 5,
      },
      {
        id: "di3",
        label: "Cancelled cheque / bank letter",
        description: "For payout verification.",
        required: true,
        acceptedFormats: ["PDF", "JPG", "PNG"],
        maxSizeMb: 5,
      },
      {
        id: "di4",
        label: "MSME certificate (if applicable)",
        required: false,
        acceptedFormats: ["PDF"],
        maxSizeMb: 5,
      },
    ],
  },
  {
    id: "drt2",
    name: "Enterprise security review",
    description: "Documents requested before sandbox / demo access.",
    category: "compliance",
    defaultTtlDays: 14,
    defaultChannels: ["email", "portal"],
    items: [
      {
        id: "di5",
        label: "Security questionnaire (completed)",
        required: true,
        acceptedFormats: ["PDF", "XLSX"],
        maxSizeMb: 10,
      },
      {
        id: "di6",
        label: "SOC 2 / ISO summary (if available)",
        required: false,
        acceptedFormats: ["PDF"],
        maxSizeMb: 10,
      },
      {
        id: "di7",
        label: "IP allowlist document",
        description: "CIDR ranges for sandbox access.",
        required: true,
        acceptedFormats: ["PDF", "TXT", "CSV"],
        maxSizeMb: 2,
      },
    ],
  },
  {
    id: "drt3",
    name: "Citizen complaint evidence",
    description: "Supporting files for grievance cases.",
    category: "support",
    defaultTtlDays: 5,
    defaultChannels: ["whatsapp", "sms"],
    items: [
      {
        id: "di8",
        label: "Photo evidence",
        required: true,
        acceptedFormats: ["JPG", "PNG"],
        maxSizeMb: 8,
      },
      {
        id: "di9",
        label: "Written statement",
        required: false,
        acceptedFormats: ["PDF", "DOCX"],
        maxSizeMb: 5,
      },
    ],
  },
];

export const MOCK_OUTREACH_DISPATCHES: OutreachDispatch[] = [
  {
    id: "od1",
    type: "document_request",
    contactId: "c1",
    contactName: "Ananya Iyer",
    contactEmail: "ananya.iyer@techcorp.in",
    subject: "Upload vendor onboarding documents",
    templateId: "drt1",
    templateName: "Vendor onboarding — India",
    channels: ["email", "whatsapp"],
    status: "in_progress",
    sentAt: "2026-06-24T09:00:00Z",
    expiresAt: "2026-07-01T18:00:00Z",
    openedAt: "2026-06-24T10:15:00Z",
    progress: { completed: 0, total: 3 },
    magicLinkToken: "vk-onboard-ananya",
    sentBy: "Priya Sharma",
    notes: "Required before contract execution.",
  },
  {
    id: "od2",
    type: "survey",
    contactId: "c2",
    contactName: "Rahul Verma",
    contactEmail: "rahul.v@buildco.in",
    subject: "How was your support experience?",
    surveyId: "sv2",
    surveyName: "Support Resolution CSAT",
    channels: ["email"],
    status: "completed",
    sentAt: "2026-06-22T14:00:00Z",
    expiresAt: "2026-06-29T18:00:00Z",
    openedAt: "2026-06-22T16:30:00Z",
    completedAt: "2026-06-22T16:35:00Z",
    magicLinkToken: "sv-csat-rahul",
    sentBy: "Neha Reddy",
  },
  {
    id: "od3",
    type: "document_request",
    contactId: "c3",
    contactName: "Sunita Patil",
    contactEmail: "sunita.p@gov.in",
    subject: "Please upload complaint evidence",
    templateId: "drt3",
    templateName: "Citizen complaint evidence",
    channels: ["whatsapp"],
    status: "sent",
    sentAt: "2026-06-24T11:00:00Z",
    expiresAt: "2026-06-29T18:00:00Z",
    progress: { completed: 0, total: 1 },
    magicLinkToken: "vk-evidence-sunita",
    sentBy: "Priya Sharma",
  },
  {
    id: "od4",
    type: "survey",
    contactId: "c1",
    contactName: "Ananya Iyer",
    contactEmail: "ananya.iyer@techcorp.in",
    subject: "Quarterly relationship check-in",
    surveyId: "sv1",
    surveyName: "Post-Purchase NPS",
    channels: ["email", "portal"],
    status: "opened",
    sentAt: "2026-06-23T08:00:00Z",
    expiresAt: "2026-06-30T18:00:00Z",
    openedAt: "2026-06-23T19:00:00Z",
    magicLinkToken: "sv-nps-ananya",
    sentBy: "Arjun Mehta",
  },
];

export const MAGIC_LINK_SESSIONS: Record<string, MagicLinkSession> = {
  "vk-onboard-ananya": {
    token: "vk-onboard-ananya",
    contactName: "Ananya Iyer",
    company: "TechCorp India",
    repName: "Priya Sharma",
    repEmail: "priya@connectcrm.in",
    purpose: "Vendor onboarding — India",
    expiresAt: "2026-07-01T18:00:00Z",
    items: DOCUMENT_REQUEST_TEMPLATES[0].items,
    completedItemIds: [],
  },
  "vk-evidence-sunita": {
    token: "vk-evidence-sunita",
    contactName: "Sunita Patil",
    company: "Municipal Services",
    repName: "Priya Sharma",
    repEmail: "priya@connectcrm.in",
    purpose: "Citizen complaint evidence",
    expiresAt: "2026-06-29T18:00:00Z",
    items: DOCUMENT_REQUEST_TEMPLATES[2].items,
    completedItemIds: [],
  },
};

export function getMagicLinkSession(token: string) {
  return MAGIC_LINK_SESSIONS[token];
}

export function getOutreachDispatch(id: string) {
  return MOCK_OUTREACH_DISPATCHES.find((d) => d.id === id);
}
