import type {
  PortalWhatsAppMessage,
  WhatsAppBotFlow,
  WhatsAppBroadcast,
  WhatsAppBusinessConfig,
  WhatsAppStats,
  WhatsAppTemplate,
  WhatsAppThread,
} from "@/lib/types/whatsapp";

export const WHATSAPP_CONFIG: WhatsAppBusinessConfig = {
  phoneNumber: "+91 80 4567 8900",
  displayName: "Connect CRM",
  businessId: "WABA-88421",
  provider: "Meta Cloud API",
  webhookStatus: "healthy",
  qualityRating: "green",
  messagingLimit: "10K / 24h",
  lastSync: "2026-06-24T09:00:00Z",
};

export const WHATSAPP_STATS: WhatsAppStats = {
  threadsOpen: 24,
  unread: 7,
  avgFirstResponseMin: 18,
  deliveryRate: 98.2,
  readRate: 76.4,
  replyRate: 34.1,
  leadsFromWa: 3100,
  templatesActive: 12,
};

export const WHATSAPP_TEMPLATES: WhatsAppTemplate[] = [
  {
    id: "wt1",
    name: "welcome_lead",
    category: "utility",
    status: "approved",
    language: "en",
    body: "Hi {{1}}, thanks for reaching out to Connect CRM. {{2}} will assist you shortly.",
    variables: ["firstName", "ownerName"],
    sent: 1240,
    delivered: 1218,
    read: 980,
    replied: 412,
    updatedAt: "2026-06-20T00:00:00Z",
  },
  {
    id: "wt2",
    name: "monsoon_offer",
    category: "marketing",
    status: "approved",
    language: "en",
    body: "Hello {{1}}, exclusive Monsoon offer: 15% off bulk orders. Reply YES for details.",
    variables: ["firstName"],
    buttons: [{ label: "View offer", type: "url" }],
    sent: 4200,
    delivered: 4100,
    read: 2800,
    replied: 890,
    updatedAt: "2026-06-22T00:00:00Z",
  },
  {
    id: "wt3",
    name: "case_update",
    category: "utility",
    status: "approved",
    language: "en",
    body: "Update on case {{1}}: {{2}}. Reply here if you need more help.",
    variables: ["caseNumber", "statusMessage"],
    sent: 680,
    delivered: 675,
    read: 520,
    replied: 145,
    updatedAt: "2026-06-18T00:00:00Z",
  },
  {
    id: "wt4",
    name: "doc_upload_request",
    category: "utility",
    status: "approved",
    language: "en",
    body: "Hi {{1}}, please upload requested documents: {{2}}",
    variables: ["firstName", "magicLink"],
    buttons: [{ label: "Upload now", type: "url" }],
    sent: 320,
    delivered: 318,
    read: 290,
    replied: 210,
    updatedAt: "2026-06-24T00:00:00Z",
  },
  {
    id: "wt5",
    name: "csat_survey",
    category: "utility",
    status: "approved",
    language: "en",
    body: "How was your support experience? Rate us: {{1}}",
    variables: ["surveyLink"],
    sent: 450,
    delivered: 448,
    read: 380,
    replied: 290,
    updatedAt: "2026-06-15T00:00:00Z",
  },
  {
    id: "wt6",
    name: "otp_portal_login",
    category: "authentication",
    status: "approved",
    language: "en",
    body: "Your Connect portal code is {{1}}. Valid for 10 minutes.",
    variables: ["otp"],
    sent: 890,
    delivered: 888,
    read: 870,
    replied: 0,
    updatedAt: "2026-06-10T00:00:00Z",
  },
  {
    id: "wt7",
    name: "reengage_cold_lead",
    category: "marketing",
    status: "pending",
    language: "hi",
    body: "नमस्ते {{1}}, क्या आप अभी भी Connect CRM में रुचि रखते हैं?",
    variables: ["firstName"],
    sent: 0,
    delivered: 0,
    read: 0,
    replied: 0,
    updatedAt: "2026-06-24T00:00:00Z",
  },
];

export const WHATSAPP_THREADS: WhatsAppThread[] = [
  {
    id: "wt-h1",
    contactId: "c1",
    contactName: "Ananya Iyer",
    phone: "+91 98765 43210",
    assignee: "Priya Sharma",
    status: "open",
    unread: true,
    lastMessageAt: "2026-06-24T10:30:00Z",
    sessionOpen: true,
    sessionExpiresAt: "2026-06-25T10:30:00Z",
    tags: ["enterprise", "hot"],
    source: "WhatsApp",
    messages: [
      {
        id: "m1",
        direction: "inbound",
        type: "text",
        body: "Hi, I need demo access for security review.",
        sentAt: "2026-06-24T09:00:00Z",
      },
      {
        id: "m2",
        direction: "outbound",
        type: "template",
        body: "Hi Ananya, thanks for reaching out. Priya Sharma will assist you shortly.",
        templateName: "welcome_lead",
        sentAt: "2026-06-24T09:02:00Z",
        status: "read",
        actor: "System",
      },
      {
        id: "m3",
        direction: "outbound",
        type: "text",
        body: "Ananya — I can provision sandbox today. Please share admin email and IP allowlist.",
        sentAt: "2026-06-24T09:15:00Z",
        status: "read",
        actor: "Priya Sharma",
      },
      {
        id: "m4",
        direction: "inbound",
        type: "text",
        body: "Admin is security@techcorp.in. IP range 103.21.44.0/24",
        sentAt: "2026-06-24T10:30:00Z",
      },
    ],
  },
  {
    id: "wt-h2",
    contactId: "c2",
    contactName: "Rahul Verma",
    phone: "+91 99887 76655",
    assignee: "Arjun Mehta",
    status: "open",
    unread: false,
    lastMessageAt: "2026-06-23T16:40:00Z",
    sessionOpen: false,
    tags: ["retail"],
    source: "Campaign",
    messages: [
      {
        id: "m5",
        direction: "outbound",
        type: "template",
        body: "Hello Rahul, exclusive Monsoon offer: 15% off bulk orders.",
        templateName: "monsoon_offer",
        sentAt: "2026-06-23T10:00:00Z",
        status: "read",
        actor: "Campaign",
      },
      {
        id: "m6",
        direction: "inbound",
        type: "text",
        body: "Is the 15% discount applicable on bulk orders?",
        sentAt: "2026-06-23T16:40:00Z",
      },
    ],
  },
  {
    id: "wt-h3",
    contactId: "c3",
    contactName: "Sunita Patil",
    phone: "+91 91234 56789",
    assignee: "Priya Sharma",
    status: "pending",
    unread: true,
    lastMessageAt: "2026-06-24T11:00:00Z",
    sessionOpen: true,
    sessionExpiresAt: "2026-06-25T11:00:00Z",
    tags: ["complaint", "citizen"],
    source: "WhatsApp",
    messages: [
      {
        id: "m7",
        direction: "inbound",
        type: "text",
        body: "COMPLAINT — No water supply Ward 12 for 48 hours",
        sentAt: "2026-06-24T08:00:00Z",
      },
      {
        id: "m8",
        direction: "outbound",
        type: "template",
        body: "Update on case CM-1042: Field team dispatched for inspection.",
        templateName: "case_update",
        sentAt: "2026-06-24T09:00:00Z",
        status: "delivered",
        actor: "System",
      },
      {
        id: "m9",
        direction: "outbound",
        type: "template",
        body: "Please upload photo evidence using secure link.",
        templateName: "doc_upload_request",
        sentAt: "2026-06-24T11:00:00Z",
        status: "sent",
        actor: "Priya Sharma",
      },
    ],
  },
  {
    id: "wt-h4",
    contactId: "c4",
    contactName: "Vikram Singh",
    phone: "+91 87654 32109",
    assignee: "Neha Reddy",
    status: "resolved",
    unread: false,
    lastMessageAt: "2026-06-22T14:00:00Z",
    sessionOpen: false,
    tags: [],
    messages: [
      {
        id: "m10",
        direction: "inbound",
        type: "text",
        body: "Thanks, demo credentials received!",
        sentAt: "2026-06-22T14:00:00Z",
      },
    ],
  },
  {
    id: "wt-h5",
    contactId: "c5",
    contactName: "Meera Krishnan",
    phone: "+91 99001 22334",
    assignee: "Priya Sharma",
    status: "open",
    unread: true,
    lastMessageAt: "2026-06-24T07:45:00Z",
    sessionOpen: true,
    sessionExpiresAt: "2026-06-25T07:45:00Z",
    tags: ["legal"],
    messages: [
      {
        id: "m11",
        direction: "outbound",
        type: "text",
        body: "Meera — NDA is ready for signature. Link sent to your email and portal.",
        sentAt: "2026-06-23T08:00:00Z",
        status: "read",
        actor: "Priya Sharma",
      },
      {
        id: "m12",
        direction: "inbound",
        type: "text",
        body: "Can you resend on WhatsApp? Email went to spam.",
        sentAt: "2026-06-24T07:45:00Z",
      },
    ],
  },
];

export const WHATSAPP_BROADCASTS: WhatsAppBroadcast[] = [
  {
    id: "wb1",
    name: "Monsoon Offer — Retail VIP",
    templateId: "wt2",
    templateName: "monsoon_offer",
    segmentName: "Retail VIP",
    status: "scheduled",
    scheduledAt: "2026-06-25T10:00:00Z",
    sent: 0,
    delivered: 0,
    read: 0,
    replied: 0,
    failed: 0,
  },
  {
    id: "wb2",
    name: "Q2 NPS — Active customers",
    templateId: "wt5",
    templateName: "csat_survey",
    segmentName: "Active customers",
    status: "sent",
    sent: 890,
    delivered: 875,
    read: 620,
    replied: 290,
    failed: 15,
  },
  {
    id: "wb3",
    name: "Vendor onboarding docs",
    templateId: "wt4",
    templateName: "doc_upload_request",
    segmentName: "New vendors",
    status: "sent",
    sent: 120,
    delivered: 118,
    read: 105,
    replied: 88,
    failed: 2,
  },
];

export const WHATSAPP_BOT_FLOWS: WhatsAppBotFlow[] = [
  {
    id: "bot1",
    name: "Lead qualification",
    status: "active",
    trigger: "New inbound message (unknown contact)",
    description: "Collect name, company, interest → create lead → assign rep",
    steps: 6,
    handoffs: 142,
    completionRate: 68,
  },
  {
    id: "bot2",
    name: "Complaint intake",
    status: "active",
    trigger: "Keyword: COMPLAINT",
    description: "Ward, issue type, photo → create case",
    steps: 5,
    handoffs: 89,
    completionRate: 72,
  },
  {
    id: "bot3",
    name: "Business hours auto-reply",
    status: "active",
    trigger: "Outside business hours",
    description: "Acknowledge + expected response time",
    steps: 2,
    handoffs: 0,
    completionRate: 100,
  },
  {
    id: "bot4",
    name: "Demo booking",
    status: "draft",
    trigger: "Keyword: DEMO",
    description: "Offer slots from calendar → book meeting",
    steps: 8,
    handoffs: 0,
    completionRate: 0,
  },
];

export const PORTAL_WHATSAPP_MESSAGES: PortalWhatsAppMessage[] = [
  {
    id: "pm1",
    direction: "outbound",
    body: "Hi Ananya — I can provision sandbox today. Please share admin email and IP allowlist.",
    sentAt: "2026-06-24T09:15:00Z",
    senderName: "Priya Sharma",
    read: true,
  },
  {
    id: "pm2",
    direction: "inbound",
    body: "Admin is security@techcorp.in. IP range 103.21.44.0/24",
    sentAt: "2026-06-24T10:30:00Z",
    senderName: "You",
    read: true,
  },
  {
    id: "pm3",
    direction: "outbound",
    body: "Thank you! Sandbox provisioning started. You'll receive credentials within 2 hours. Case CM-1051 updated.",
    sentAt: "2026-06-24T10:45:00Z",
    senderName: "Priya Sharma",
    read: true,
  },
  {
    id: "pm4",
    direction: "outbound",
    body: "Reminder: Please upload your company PAN card using the secure link sent earlier.",
    sentAt: "2026-06-24T11:00:00Z",
    senderName: "Priya Sharma",
    read: false,
  },
];

export function getWhatsAppThread(id: string) {
  return WHATSAPP_THREADS.find((t) => t.id === id);
}

export function getWhatsAppThreadsForContact(contactId: string) {
  return WHATSAPP_THREADS.filter((t) => t.contactId === contactId);
}

export function getWhatsAppTemplate(id: string) {
  return WHATSAPP_TEMPLATES.find((t) => t.id === id);
}

export function getRepWhatsAppStats(assignee: string) {
  const threads = WHATSAPP_THREADS.filter((t) => t.assignee === assignee);
  return {
    threadsOpen: threads.filter((t) => t.status === "open" || t.status === "pending").length,
    unread: threads.filter((t) => t.unread).length,
    avgFirstResponseMin: 14,
  };
}
